name: AntiFarmReloaded
version: $version
authors:
   - sillycorn
   - oTuin
main: core.AntiFarmPlugin
api-version: 1.20 #1.20.5
description: Multipurpose AFK farm blocker Reloaded.
commands:
   antifarmreloaded:
   antifarm:
   antifarm reload:
   antifarmreloaded reload: