name: AntiFarmReloaded
version: $version
authors:
   - sillycorn
   - oTuin
main: core.AntiFarmPlugin
api-version: 1.19
description: Multipurpose AFK farm blocker Reloaded.
commands:
   antifarmreloaded:
   antifarm: